Repository ormcamp-fe-3rd/bunnies-page, pull requests merged in 2024-11, with the labels that each got.

#1 [나슬기] 멤버 페이지 응원 메세지 UI 구현
  .prettierrc.cjs
  PJT_HISTORY.md
  README.md
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/member/msg-bg-emoji.png
  member.html
  tailwind.config.js
Labels: html / css

#11 [반재영] 메인페이지 멤버 섹션 카드 구성
  assets/css/tailwindcss.output.css
  assets/images/main-member/main-danielle-frame.png
  assets/images/main-member/main-danielle.jpeg
  assets/images/main-member/main-haerin-frame.png
  assets/images/main-member/main-haerin.jpeg
  assets/images/main-member/main-hanni-frame.png
  assets/images/main-member/main-hanni.jpeg
  assets/images/main-member/main-hyein-frame.png
  assets/images/main-member/main-hyein.jpeg
  assets/images/main-member/main-minji-frame.png
  assets/images/main-member/main-minji.jpeg
  index.html
Labels: html / css

#14 [김혜빈] 앨범 페이지 플레이리스트 UI 구현
  album.html
  assets/css/album.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/albums/NEWJEANS_PLAYLIST_QR_image.png
  assets/images/albums/NEWJEANS_PLAYLIST_QR_image.svg
  assets/images/albums/PlayList_logo.png
  assets/images/albums/cd_newjeans.png
  assets/images/albums/play-circle.png
  assets/images/albums/previous-1.png
  assets/images/albums/previous.png
  assets/images/albums/white-crumpled-paper-texture-background.jpg
  assets/images/member/Team-photo-minji_01.png
  assets/images/member/Team-photo-minji_02.png
  assets/images/member/Team-photo-minji_03.png
  assets/images/member/Team-photo-minji_04.png
  assets/images/member/Team-photo-minji_05.png
  assets/images/member/Team-photo-minji_06.png
  assets/images/member/Team-photo-minji_07.png
  assets/images/member/photo-page-1.png
  assets/images/member/photo-page-2.png
  assets/images/member/photo-page-3.png
  assets/images/member/photo-page-4.png
  assets/images/member/photo-page-5.png
  assets/images/member/photo-page-none.png
  member.css
  member.html
  package-lock.json
Labels: html / css

#16 [김혜빈] 갤러리,페이지네이션 UI 구현
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/images/member/Team-photo-minji_01.png
  assets/images/member/Team-photo-minji_02.png
  assets/images/member/Team-photo-minji_03.png
  assets/images/member/Team-photo-minji_04.png
  assets/images/member/Team-photo-minji_05.png
  assets/images/member/Team-photo-minji_06.png
  assets/images/member/Team-photo-minji_07.png
  assets/images/member/photo-page-1.png
  assets/images/member/photo-page-2.png
  assets/images/member/photo-page-3.png
  assets/images/member/photo-page-4.png
  assets/images/member/photo-page-5.png
  assets/images/member/photo-page-none.png
  member.html
  package-lock.json
Labels: html / css

#20 [김혜빈] Album/playlist UI 구현
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/js/member.js
Labels: html / css

#19 [김혜빈 & 나슬기] 멤버 페이지 구현
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/images/member/Team-photo-minji_01.png
  assets/images/member/Team-photo-minji_02.png
  assets/images/member/Team-photo-minji_03.png
  assets/images/member/Team-photo-minji_04.png
  assets/images/member/Team-photo-minji_05.png
  assets/images/member/Team-photo-minji_06.png
  assets/images/member/Team-photo-minji_07.png
  assets/images/member/msg-bg-emoji.png
  assets/images/member/photo-page-1.png
  assets/images/member/photo-page-2.png
  assets/images/member/photo-page-3.png
  assets/images/member/photo-page-4.png
  assets/images/member/photo-page-5.png
  assets/images/member/photo-page-none.png
  assets/js/member.js
  member.html
  package-lock.json
Labels: html / css

#23 [한솔] home/memeber와 home/album 머지 후, home/main에 머지 요청
  PJT_HISTORY.md
  README.md
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/album/album_img/1stEP.jpg
  assets/images/album/album_img/Ditto.jpg
  assets/images/album/album_img/GetUp.webp
  assets/images/album/album_img/HowSweet.webp
  assets/images/album/album_img/OMG.jpg
  assets/images/album/album_img/Supernatural.webp
  assets/images/album/mac.png
  assets/images/album/newjeans-bg-bubblegum.png
  assets/images/album/pc-outside-background.jpg_large
  assets/images/album/room-bg.jpg
  assets/images/album/sea-bg.jpeg
  index.html
  package-lock.json
  tailwind.config.js
Labels: html / css

#27 [이현호] 메인 페이지 UI 머지
  .gitignore
  assets/css/home.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  index.html
  tailwind.config.js
Labels: html / css

#28 [반재영] - 메인 페이지 태그 중복, 홈-멤버카드 width 수정
  assets/css/tailwindcss.output.css
  index.html
Labels: 버그 수정, html / css

#30 [나슬기] 헤더 풋터 반응형 적용
  assets/css/home.css
  assets/css/tailwindcss.output.css
  index.html
Labels: html / css

#33 [반재영] - 앨범페이지 플레이리스트 기능 구현(버튼 기능, cd 애니메이션, 영수증 변경)
  .gitignore
  .prettierrc.cjs
  PJT_HISTORY.md
  README.md
  album.html
  assets/css/album.css
  assets/css/home.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/album/album_img/1stEP.jpg
  assets/images/album/album_img/Ditto.jpg
  assets/images/album/album_img/GetUp.webp
  assets/images/album/album_img/HowSweet.webp
  assets/images/album/album_img/OMG.jpg
  assets/images/album/album_img/Supernatural.webp
  assets/images/album/mac.png
  assets/images/album/newjeans-bg-bubblegum.png
  assets/images/album/pc-outside-background.jpg_large
  assets/images/album/room-bg.jpg
  assets/images/album/sea-bg.jpeg
  assets/images/albums/paused-circle.png
  assets/images/header/homeMenuicon1.svg
  assets/images/header/homeMenuicon2.svg
  assets/images/header/homeMenuicon3.svg
  assets/images/header/homeMenuicon4.svg
  assets/images/header/homeMenuicon5.svg
  assets/images/main-member/main-danielle-frame.png
  assets/images/main-member/main-danielle.jpeg
  assets/images/main-member/main-haerin-frame.png
  assets/images/main-member/main-haerin.jpeg
  assets/images/main-member/main-hanni-frame.png
  assets/images/main-member/main-hanni.jpeg
  assets/images/main-member/main-hyein-frame.png
  assets/images/main-member/main-hyein.jpeg
  assets/images/main-member/main-minji-frame.png
  assets/images/main-member/main-minji.jpeg
  assets/images/member/msg-bg-emoji.png
  assets/js/album-playlist.js
  index.html
  member.css
  member.html
  tailwind.config.js
Labels: 버그 수정, JS

#29 [김혜빈] 멤버페이지 페이지네이션 기능 구현
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/images/member/dani/Team-photo-dani_01.png
  assets/images/member/dani/Team-photo-dani_02.png
  assets/images/member/dani/Team-photo-dani_03.png
  assets/images/member/dani/Team-photo-dani_04.png
  assets/images/member/dani/Team-photo-dani_05.png
  assets/images/member/dani/Team-photo-dani_06.png
  assets/images/member/dani/Team-photo-dani_07.png
  assets/images/member/haerin/Team-photo-haerin_01.png
  assets/images/member/haerin/Team-photo-haerin_02.png
  assets/images/member/haerin/Team-photo-haerin_03.png
  assets/images/member/haerin/Team-photo-haerin_04.png
  assets/images/member/haerin/Team-photo-haerin_05.png
  assets/images/member/haerin/Team-photo-haerin_06.png
  assets/images/member/haerin/Team-photo-haerin_07.png
  assets/images/member/hanni/Team-photo-hanni_01.png
  assets/images/member/hanni/Team-photo-hanni_02.png
  assets/images/member/hanni/Team-photo-hanni_03.png
  assets/images/member/hanni/Team-photo-hanni_04.png
  assets/images/member/hanni/Team-photo-hanni_05.png
  assets/images/member/hanni/Team-photo-hanni_06.png
  assets/images/member/hanni/Team-photo-hanni_07.png
  assets/images/member/hyein/Team-photo-hyein_01.png
  assets/images/member/hyein/Team-photo-hyein_02.png
  assets/images/member/hyein/Team-photo-hyein_03.png
  assets/images/member/hyein/Team-photo-hyein_04.png
  assets/images/member/hyein/Team-photo-hyein_05.png
  assets/images/member/hyein/Team-photo-hyein_06.png
  assets/images/member/hyein/Team-photo-hyein_07.png
  assets/js/member.js
  member.html
Labels: JS

#36 [반재영] 멤버페이지 메세지 기능 구현
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/js/member-message.js
  member.html
  tailwind.config.js
Labels: JS

#37 [김혜빈] 앨범페이지 3d 회전 기능 구현
  album.html
  assets/css/album.css
  assets/css/home.css
  assets/css/tailwindcss.output.css
  assets/images/header/logo-ador.svg
  assets/js/three.js
  index.html
Labels: JS

#35 [김혜빈] 앨범페이지 영수증 플레이리스트 줄 길이 변경
  album.html
  assets/css/album.css
Labels: html / css

#38 [나슬기] 앨범페이지 플레이리스트 영역 고정 및 회전 각도 유지
  album.html
  assets/css/album.css
  assets/js/album-playlist.js
Labels: JS

#40 [박한솔 & 반재영] 멤버페이지 기능 구현 중간 병합
  assets/css/member.css
  assets/css/tailwindcss.output.css
  assets/images/member/dani/Team-photo-dani_01.png
  assets/images/member/dani/Team-photo-dani_02.png
  assets/images/member/dani/Team-photo-dani_03.png
  assets/images/member/dani/Team-photo-dani_04.png
  assets/images/member/dani/Team-photo-dani_05.png
  assets/images/member/dani/Team-photo-dani_06.png
  assets/images/member/dani/Team-photo-dani_07.png
  assets/images/member/haerin/Team-photo-haerin_01.png
  assets/images/member/haerin/Team-photo-haerin_02.png
  assets/images/member/haerin/Team-photo-haerin_03.png
  assets/images/member/haerin/Team-photo-haerin_04.png
  assets/images/member/haerin/Team-photo-haerin_05.png
  assets/images/member/haerin/Team-photo-haerin_06.png
  assets/images/member/haerin/Team-photo-haerin_07.png
  assets/images/member/hanni/Team-photo-hanni_01.png
  assets/images/member/hanni/Team-photo-hanni_02.png
  assets/images/member/hanni/Team-photo-hanni_03.png
  assets/images/member/hanni/Team-photo-hanni_04.png
  assets/images/member/hanni/Team-photo-hanni_05.png
  assets/images/member/hanni/Team-photo-hanni_06.png
  assets/images/member/hanni/Team-photo-hanni_07.png
  assets/images/member/hyein/Team-photo-hyein_01.png
  assets/images/member/hyein/Team-photo-hyein_02.png
  assets/images/member/hyein/Team-photo-hyein_03.png
  assets/images/member/hyein/Team-photo-hyein_04.png
  assets/images/member/hyein/Team-photo-hyein_05.png
  assets/images/member/hyein/Team-photo-hyein_06.png
  assets/images/member/hyein/Team-photo-hyein_07.png
  assets/js/member-message.js
  assets/js/member.js
  member.html
  tailwind.config.js
Labels: JS

#43 [이현호] 합침 오류 수정 및 색상 추가
  assets/css/tailwindcss.output.css
  assets/images/album/flo.svg
  assets/images/album/genie.svg
  assets/images/album/melon.svg
  index.html
Labels: 버그 수정

#45 [한솔] 멤버카드 드래그&드롭 움직임 제한 기능 향상
  assets/css/tailwindcss.output.css
  assets/images/album/flo.svg
  assets/images/album/genie.svg
  assets/images/album/melon.svg
  assets/js/card-rotate.js
  assets/js/home.js
  assets/js/member.js
  index.html
  member.html
Labels: JS, 기능 향상

#49 [나슬기] 페이지별 커서 이미지 변경
  album.html
  assets/css/home.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/cursor/bunnie.png
  assets/images/cursor/clickMe.png
  assets/images/cursor/korean.png
  assets/images/cursor/rounded.png
  assets/js/member.js
  index.html
  member.html
Labels: html / css

#48 [반재영] 멤버페이지 메세지 기능 구현(localStorage 적용)
  assets/css/tailwindcss.output.css
  assets/js/member-message.js
  member.html
Labels: JS

#50 [한솔] 멤버 카드 내에 TMI 정보 추가
  assets/css/member.css
  member.html
Labels: html / css, 컨텐츠 관련

#42 [김혜빈} 3d 조명,회전값 추가 및 수정
  PJT_CHECKLIST.md
  PJT_HISTORY.md
  album.html
  assets/audio/ASAP.mp3
  assets/audio/Attention.mp3
  assets/audio/Bubble-Gum(Instrumental).mp3
  assets/audio/Bubble-Gum.mp3
  assets/audio/Cookie.mp3
  assets/audio/Cool-With-You.mp3
  assets/audio/Ditto.mp3
  assets/audio/ETA.mp3
  assets/audio/Get-Up.mp3
  assets/audio/How-Sweet(Instrumental).mp3
  assets/audio/How-Sweet.mp3
  assets/audio/Hurt.mp3
  assets/audio/Hype-Boy.mp3
  assets/audio/New-Jeans.mp3
  assets/audio/OMG.mp3
  assets/audio/Right-Now(Instrumental).mp3
  assets/audio/Right-Now.mp3
  assets/audio/Super-Shy.mp3
  assets/audio/Supernatural(Instrumental).mp3
  assets/audio/Supernatural.mp3
  assets/css/album.css
  assets/css/tailwindcss.output.css
  assets/images/album/3dTexture/newjeans/back.png
  assets/images/album/3dTexture/newjeans/bottom.png
  assets/images/album/3dTexture/newjeans/front.png
  assets/images/album/3dTexture/newjeans/left.png
  assets/images/album/3dTexture/newjeans/right.png
  assets/images/album/3dTexture/newjeans/top.png
  assets/images/album/3dTexture/omg&ditto/back.png
  assets/images/album/3dTexture/omg&ditto/bottom.png
  assets/images/album/3dTexture/omg&ditto/front.png
  assets/images/album/3dTexture/omg&ditto/left.png
  assets/images/album/3dTexture/omg&ditto/right.png
  assets/images/album/3dTexture/omg&ditto/top.png
  assets/js/album-playlist.js
  assets/js/three.js
Labels: JS

#51 [한솔 & 재영] 멤버 페이지 콘텐츠 내용 보충
  assets/css/member.css
  assets/js/member-message.js
  assets/js/member.js
  member.html
Labels: html / css, 컨텐츠 관련

#53 [반재영] 메인페이지 멤버카드 클릭시 해당 멤버페이지로 연결
  album.html
  assets/css/album.css
  assets/css/member.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/album/flo.svg
  assets/images/album/genie.svg
  assets/images/album/melon.svg
  assets/images/albums/paused-circle.png
  assets/images/header/logo-ador.svg
  assets/images/member/dani/Team-photo-dani_01.png
  assets/images/member/dani/Team-photo-dani_02.png
  assets/images/member/dani/Team-photo-dani_03.png
  assets/images/member/dani/Team-photo-dani_04.png
  assets/images/member/dani/Team-photo-dani_05.png
  assets/images/member/dani/Team-photo-dani_06.png
  assets/images/member/dani/Team-photo-dani_07.png
  assets/images/member/haerin/Team-photo-haerin_01.png
  assets/images/member/haerin/Team-photo-haerin_02.png
  assets/images/member/haerin/Team-photo-haerin_03.png
  assets/images/member/haerin/Team-photo-haerin_04.png
  assets/images/member/haerin/Team-photo-haerin_05.png
  assets/images/member/haerin/Team-photo-haerin_06.png
  assets/images/member/haerin/Team-photo-haerin_07.png
  assets/images/member/hanni/Team-photo-hanni_01.png
  assets/images/member/hanni/Team-photo-hanni_02.png
  assets/images/member/hanni/Team-photo-hanni_03.png
  assets/images/member/hanni/Team-photo-hanni_04.png
  assets/images/member/hanni/Team-photo-hanni_05.png
  assets/images/member/hanni/Team-photo-hanni_06.png
  assets/images/member/hanni/Team-photo-hanni_07.png
  assets/images/member/hyein/Team-photo-hyein_01.png
  assets/images/member/hyein/Team-photo-hyein_02.png
  assets/images/member/hyein/Team-photo-hyein_03.png
  assets/images/member/hyein/Team-photo-hyein_04.png
  assets/images/member/hyein/Team-photo-hyein_05.png
  assets/images/member/hyein/Team-photo-hyein_06.png
  assets/images/member/hyein/Team-photo-hyein_07.png
  assets/js/album-playlist.js
  assets/js/card-rotate.js
  assets/js/home.js
  assets/js/member-message.js
  assets/js/member.js
  assets/js/three.js
  index.html
  member.html
  tailwind.config.js
Labels: JS

#57 [김혜빈] 3d 텍스처 추가 및 변경
  album.html
  assets/css/home.css
  assets/css/tailwindcss.input.css
  assets/css/tailwindcss.output.css
  assets/images/album/3dTexture/getup/back.png
  assets/images/album/3dTexture/getup/bottom.png
  assets/images/album/3dTexture/getup/front.png
  assets/images/album/3dTexture/getup/left.png
  assets/images/album/3dTexture/getup/right.png
  assets/images/album/3dTexture/getup/top.png
  assets/images/album/3dTexture/howSweet/back.png
  assets/images/album/3dTexture/howSweet/bottom.png
  assets/images/album/3dTexture/howSweet/front.png
  assets/images/album/3dTexture/howSweet/left.png
  assets/images/album/3dTexture/howSweet/right.png
  assets/images/album/3dTexture/howSweet/top.png
  assets/images/album/3dTexture/omg&ditto/back.png
  assets/images/album/3dTexture/omg&ditto/bottom.png
  assets/images/album/3dTexture/omg&ditto/front.png
  assets/images/album/3dTexture/omg&ditto/left.png
  assets/images/album/3dTexture/omg&ditto/right.png
  assets/images/album/3dTexture/omg&ditto/top.png
  assets/images/album/3dTexture/supernatural/buttom.png
  assets/images/album/3dTexture/supernatural/front.png
  assets/images/album/3dTexture/supernatural/left.png
  assets/images/album/3dTexture/supernatural/right.png
  assets/images/album/3dTexture/supernatural/top.png
  assets/images/cursor/bunnie.png
  assets/images/cursor/clickMe.png
  assets/images/cursor/korean.png
  assets/images/cursor/rounded.png
  assets/js/album-playlist.js
  assets/js/member.js
  assets/js/three.js
  index.html
  member.html
Labels: JS, 도움 요청

#59 [반재영] 메인페이지 멤버카드 섹션 함수 js 파일 분리
  assets/js/home.js
  assets/js/member.js
  index.html
Labels: 기능 향상

#58 [김혜빈 & 나슬기] 앨범 페이지 수정 사항 합치기
  album.html
  assets/css/tailwindcss.output.css
  assets/images/album/3dTexture/getup/back.png
  assets/images/album/3dTexture/getup/bottom.png
  assets/images/album/3dTexture/getup/front.png
  assets/images/album/3dTexture/getup/left.png
  assets/images/album/3dTexture/getup/right.png
  assets/images/album/3dTexture/getup/top.png
  assets/images/album/3dTexture/howSweet/back.png
  assets/images/album/3dTexture/howSweet/bottom.png
  assets/images/album/3dTexture/howSweet/front.png
  assets/images/album/3dTexture/howSweet/left.png
  assets/images/album/3dTexture/howSweet/right.png
  assets/images/album/3dTexture/howSweet/top.png
  assets/images/album/3dTexture/supernatural/buttom.png
  assets/images/album/3dTexture/supernatural/front.png
  assets/images/album/3dTexture/supernatural/left.png
  assets/images/album/3dTexture/supernatural/right.png
  assets/images/album/3dTexture/supernatural/top.png
  assets/js/album-playlist.js
  assets/js/three.js
Labels: 버그 수정, JS

#55 [이현호] 팝업 앨범이미지를 CD 모양 호버 추가
  index.html
Labels: JS

#63 [한솔] 자잘한 버그 수정
  assets/css/member.css
  assets/js/member.js
  member.html
Labels: 버그 수정, JS, 기능 향상

#66 [한솔, 재영] 기능 부분 피드백 반영하여 버그 수정
  album.html
  assets/css/album.css
  assets/css/tailwindcss.output.css
  assets/js/album-playlist.js
  assets/js/member.js
  assets/js/three.js
  index.html
  member.html
Labels: 버그 수정, JS
